"""empty message

Revision ID: 77bb636bcad2
Revises: 
Create Date: 2026-08-28 07:36:35.142178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77bb636bcad2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'assignments',
        'materials',
        type_=sa.JSON(),
        existing_type=sa.VARCHAR(),  # or whatever your previous type was
        postgresql_using='materials::json'
    )
    op.alter_column('assignments', 'materials',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('assignments', 'dueDate',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('assignments', 'due_date_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('assignments', 'driveId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('driveId', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('assignments', 'due_date_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('assignments', 'dueDate',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('assignments', 'materials',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
