"""making coursename not nullable

Revision ID: 9fa0e7143658
Revises: 77bb636bcad2
Create Date: 2026-08-28 08:23:07.613359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa0e7143658'
down_revision: Union[str, Sequence[str], None] = '77bb636bcad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add column as nullable so PostgreSQL accepts it
    op.add_column('assignments', sa.Column('coursename', sa.String(), nullable=True))
    
    # 2. Populate existing rows with a default string value
    op.execute("UPDATE assignments SET coursename = 'Unassigned' WHERE coursename IS NULL")
    
    # 3. Enforce the NOT NULL constraint
    op.alter_column('assignments', 'coursename', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'coursename')
    # ### end Alembic commands ###
